"""Geprüfte Faktensammlung für den kostenlosen Offline-Modus.

Seit 01.10.2026 läuft Faktastisch ohne bezahlte API (Emre: "lokal ohne
Kosten"). Ein lokales Modell schrieb zu oft Falsches (1 von 18 Fakten
bestand die Prüfung), deshalb kommen die Texte aus dieser Sammlung. Sie wurde
von Claude in einer Sitzung über das Abo geschrieben - ohne API-Kosten - und
nur mit gut belegten Fakten samt Quelle befüllt.

Nachschub: Der wöchentliche Kanal-Agent ergänzt hier neue Einträge (Regeln
in ~/Projects/kanal-waechter/AGENTEN.md). Jeder Titel darf nur einmal laufen;
local_content.py prüft gegen die gesamte Historie.

Felder wie in local_content.FACTS, plus eigene `image_prompts` je Fakt.
"""

FAKTENBANK = [
    # ------------------------------------------------------------- Geschichte
    {
        "category": "Geschichte",
        "title": "Australien verlor einen Krieg gegen Emus",
        "hook": "Soldaten gegen Vögel – die Vögel gewannen",
        "body": "1932 hatten Farmer in Westaustralien ein Problem: Zehntausende Emus fraßen ihre Felder kahl. Also schickte die Regierung Soldaten mit Maschinengewehren. Der Plan klang einfach, scheiterte aber komplett. Die Emus liefen in kleinen Gruppen auseinander, sobald geschossen wurde, und waren schneller, als die Soldaten zielen konnten. Nach wenigen Wochen wurde die Aktion abgebrochen. Die Presse nannte das Ganze spöttisch den Emu-Krieg. Und die Emus? Die gibt es dort bis heute in großer Zahl.",
        "cta": "Wer hätte bei dir gewonnen – Soldaten oder Emus?",
        "tags": ["Geschichte", "Australien", "Emu-Krieg", "Kurioses", "Wissen"],
        "sources": ["Australian War Memorial: The Emu War, 1932"],
        "image_prompts": [
            "flock of emus running across dry Australian wheat field, 1930s, cinematic, no text",
            "vintage 1930s army truck on dusty outback road, sepia film look, no text",
            "close-up of an emu looking into the camera, golden hour, no text",
            "empty wheat field with scattered emu footprints, dramatic sky, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "1518 tanzten Hunderte Menschen tagelang",
        "hook": "Eine Stadt konnte nicht mehr aufhören zu tanzen",
        "body": "Im Sommer 1518 begann in Straßburg eine Frau mitten auf der Straße zu tanzen. Sie hörte nicht auf, Tag für Tag. Bald tanzten Dutzende andere mit, nach zeitgenössischen Berichten schließlich Hunderte Menschen. Die Stadtoberen hielten Tanzen zuerst für die Heilung und ließen sogar Musiker spielen. Das machte alles schlimmer. Historiker sprechen heute von einer Tanzepidemie und vermuten eine Massenreaktion auf Hunger, Krankheit und Angst. Erklärt ist sie bis heute nicht vollständig.",
        "cta": "Hättest du an so etwas geglaubt, wenn du es nicht schwarz auf weiß lesen würdest?",
        "tags": ["Geschichte", "Mittelalter", "Straßburg", "Tanzwut", "Mysterium"],
        "sources": ["John Waller: A Time to Dance, a Time to Die (2008)"],
        "image_prompts": [
            "medieval town square at dusk with crowd of dancing silhouettes, painterly, no text",
            "old cobblestone street in a 16th century European town, cinematic, no text",
            "medieval musicians with drums and pipes, oil painting style, no text",
            "worn leather shoes on cobblestones, dramatic light, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "Der Große Brand von London: nur 6 offizielle Tote",
        "hook": "Eine ganze Stadt brannte – kaum Tote gezählt",
        "body": "1666 brannte London vier Tage lang. Das Feuer zerstörte über 13.000 Häuser und fast 90 Kirchen, darunter die alte St. Paul's Cathedral. Trotzdem wurden offiziell nur sechs Todesopfer verzeichnet. Historiker halten die echte Zahl für deutlich höher, weil arme Menschen damals oft gar nicht registriert wurden. Das Feuer begann übrigens in einer Bäckerei in der Pudding Lane. Danach baute London neu – mit Ziegeln und Stein statt Holz.",
        "cta": "Glaubst du die offizielle Zahl?",
        "tags": ["Geschichte", "London", "Feuer", "1666", "England"],
        "sources": ["Museum of London: The Great Fire of London"],
        "image_prompts": [
            "17th century London skyline engulfed in flames at night, painterly, no text",
            "old wooden bakery oven glowing, historical, no text",
            "old St Pauls cathedral silhouette behind smoke, cinematic, no text",
            "rebuilt brick and stone London street, 17th century style, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "Die Chinesische Mauer sieht man nicht aus dem All",
        "hook": "Dieser berühmte Fakt ist einfach falsch",
        "body": "Vielleicht hast du gehört, die Chinesische Mauer sei das einzige Bauwerk, das man vom Weltall aus sieht. Das stimmt nicht. Die Mauer ist zwar extrem lang, aber meist nur wenige Meter breit und hat fast dieselbe Farbe wie die Landschaft drumherum. Aus der Umlaufbahn mit bloßem Auge ist sie praktisch unsichtbar. Das bestätigen Astronauten, darunter Chinas erster Raumfahrer Yang Liwei. Mit Kamera und Zoom sieht man sie, aber nicht einfach durchs Fenster.",
        "cta": "Welchen Mythos hast du auch geglaubt?",
        "tags": ["Geschichte", "China", "Mythos", "Weltraum", "Wissen"],
        "sources": ["NASA Earth Observatory: Great Wall of China"],
        "image_prompts": [
            "Great Wall of China winding over green mountains, aerial, no text",
            "view of Earth from orbit through spacecraft window, no text",
            "astronaut silhouette looking down at Earth, cinematic, no text",
            "close-up of ancient weathered wall stones, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "Wikinger trugen nie Hörner am Helm",
        "hook": "Das berühmteste Wikinger-Bild ist erfunden",
        "body": "Wikinger mit Hörnern auf dem Helm – das Bild kennt jeder. Archäologisch gibt es dafür aber keinen Beleg. Der einzige gut erhaltene Wikingerhelm, gefunden in Norwegen, ist schlicht und ohne Hörner. Im Kampf wären Hörner auch unpraktisch gewesen. Woher kommt das Bild dann? Vor allem aus dem 19. Jahrhundert: Für eine Aufführung von Richard Wagners Ring des Nibelungen entwarf ein Kostümbildner Helme mit Hörnern. Seitdem hält sich das Bild hartnäckig.",
        "cta": "Hättest du das gedacht?",
        "tags": ["Geschichte", "Wikinger", "Mythos", "Skandinavien", "Archäologie"],
        "sources": ["Museum of Cultural History, Oslo: Gjermundbu helmet"],
        "image_prompts": [
            "simple iron Viking helmet without horns on dark background, museum light, no text",
            "Viking longship on a misty fjord, cinematic, no text",
            "19th century opera stage with dramatic lighting, no text",
            "Nordic coastline with dramatic clouds, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "Der Hundertjährige Krieg dauerte 116 Jahre",
        "hook": "Hundert Jahre? Nicht ganz",
        "body": "Der Hundertjährige Krieg zwischen England und Frankreich hat einen irreführenden Namen. Er begann 1337 und endete 1453, das sind 116 Jahre. Gekämpft wurde allerdings nicht ununterbrochen: Es gab lange Waffenstillstände und Pausen. Den Namen bekam der Krieg erst später von Historikern. In dieser Zeit wurde auch Jeanne d'Arc berühmt, die die Franzosen anführte. Am Ende verlor England fast alle Gebiete in Frankreich.",
        "cta": "Welcher Name in der Geschichte ist noch so irreführend?",
        "tags": ["Geschichte", "Mittelalter", "Frankreich", "England", "Krieg"],
        "sources": ["Encyclopaedia Britannica: Hundred Years' War"],
        "image_prompts": [
            "medieval knights on a misty battlefield, painterly, no text",
            "medieval castle in France at sunrise, no text",
            "armor and swords on a wooden table, dramatic light, no text",
            "old parchment map of England and France, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "Diese Schlacht fand nach dem Friedensvertrag statt",
        "hook": "Der Krieg war vorbei – sie wussten es nicht",
        "body": "Im Dezember 1814 unterzeichneten die USA und Großbritannien in Belgien einen Friedensvertrag. Doch Nachrichten reisten damals per Schiff, und das dauerte Wochen. Im Januar 1815 kämpften beide Seiten deshalb noch die Schlacht von New Orleans – mit Hunderten Toten und Verwundeten auf britischer Seite. Niemand vor Ort wusste, dass der Frieden schon beschlossen war. Eine ganze Schlacht, die es nur gab, weil keine Nachricht schnell genug war.",
        "cta": "Was wäre heute anders, wenn Nachrichten wieder so langsam wären?",
        "tags": ["Geschichte", "USA", "1815", "Schlacht", "Kurioses"],
        "sources": ["National Park Service: Battle of New Orleans"],
        "image_prompts": [
            "early 19th century sailing ship on rough sea, oil painting style, no text",
            "historic swamp landscape near a river at dawn, no text",
            "quill pen and sealed letter on a desk, candlelight, no text",
            "cannon smoke over a field, painterly, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "Ötzi hatte 61 Tätowierungen",
        "hook": "Ein 5.300 Jahre alter Mann – tätowiert",
        "body": "1991 fanden Wanderer in den Ötztaler Alpen eine Leiche im Eis. Es war kein Unfallopfer von damals, sondern ein Mann, der vor etwa 5.300 Jahren gestorben war: Ötzi. Forscher zählten auf seinem Körper 61 Tätowierungen, meist kleine Linien und Kreuze. Sie sitzen oft dort, wo Gelenke und Rücken schmerzen. Deshalb vermuten viele, dass die Tattoos eine Art frühe Behandlung waren. Ötzi ist eine der ältesten tätowierten Menschen, die man kennt.",
        "cta": "Würdest du dir ein Tattoo als Heilmittel stechen lassen?",
        "tags": ["Geschichte", "Ötzi", "Alpen", "Archäologie", "Steinzeit"],
        "sources": ["Südtiroler Archäologiemuseum: Ötzi"],
        "image_prompts": [
            "snowy alpine glacier pass under blue sky, no text",
            "ancient stone age tools and leather on a rock, museum lighting, no text",
            "mountain hiker silhouette on a ridge, cinematic, no text",
            "close-up of ice with trapped air bubbles, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "Die Pyramiden bauten keine Sklaven",
        "hook": "Die Bauarbeiter der Pyramiden bekamen Lohn",
        "body": "Lange hieß es, Sklaven hätten die Pyramiden von Gizeh gebaut. Ausgrabungen zeigen ein anderes Bild. Neben den Pyramiden fanden Archäologen eine Arbeiterstadt mit Bäckereien, Unterkünften und Gräbern. Die Arbeiter wurden mit Brot, Bier und Fleisch versorgt und in der Nähe der Könige ehrenvoll bestattet. Viele kamen wohl als bezahlte Arbeitskräfte oder im Rahmen einer staatlichen Dienstpflicht. Harte Arbeit war es trotzdem – aber eben keine Sklaverei im klassischen Sinn.",
        "cta": "Was hast du in der Schule über die Pyramiden gelernt?",
        "tags": ["Geschichte", "Ägypten", "Pyramiden", "Archäologie", "Mythos"],
        "sources": ["Ancient Egypt Research Associates (AERA): Lost City of the Pyramid Builders"],
        "image_prompts": [
            "pyramids of Giza at sunrise with desert haze, cinematic, no text",
            "ancient Egyptian workers village ruins, archaeological dig, no text",
            "ancient bread and clay jars on a stone table, no text",
            "massive limestone blocks close-up, dramatic light, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "Mammuts lebten noch, als die Pyramiden standen",
        "hook": "Mammuts und Pyramiden – zur selben Zeit",
        "body": "Die große Pyramide von Gizeh wurde vor rund 4.500 Jahren gebaut. Zu dieser Zeit lebten noch Mammuts. Nicht überall, aber auf der abgelegenen Wrangelinsel im Nordpolarmeer überlebte eine kleine Gruppe bis vor etwa 4.000 Jahren. Während in Ägypten also schon riesige Steinbauten standen, zogen ganz im Norden noch die letzten Wollhaarmammuts umher. Die Steinzeit und die Hochkulturen liegen zeitlich viel näher beieinander, als man denkt.",
        "cta": "Welcher Zeitvergleich hat dich schon mal umgehauen?",
        "tags": ["Geschichte", "Mammut", "Pyramiden", "Eiszeit", "Zeitvergleich"],
        "sources": ["Vartanyan et al., Nature (1993): Holocene dwarf mammoths from Wrangel Island"],
        "image_prompts": [
            "woolly mammoth walking through arctic tundra, cinematic, no text",
            "remote snowy island coastline in the Arctic, no text",
            "pyramids in the desert under a starry sky, no text",
            "mammoth tusk lying in frozen ground, no text",
        ],
    },
    {
        "category": "Geschichte",
        "title": "Die älteste Universität der Welt gründete eine Frau",
        "hook": "Eine Frau gründete die älteste Universität",
        "body": "Die Universität al-Qarawiyyin in Fès, Marokko, gilt als die älteste noch bestehende Universität der Welt. Gegründet wurde sie im Jahr 859 – von einer Frau: Fatima al-Fihri. Sie war die Tochter eines wohlhabenden Händlers und investierte ihr Erbe in eine Moschee mit Lehrbetrieb. Daraus wurde über die Jahrhunderte eine Universität. Sie ist älter als Oxford und Bologna und bildet bis heute Studierende aus.",
        "cta": "Hast du von Fatima al-Fihri schon gehört?",
        "tags": ["Geschichte", "Marokko", "Universität", "Bildung", "Fès"],
        "sources": ["UNESCO World Heritage: Medina of Fez", "Guinness World Records: Oldest existing university"],
        "image_prompts": [
            "ornate Moroccan courtyard with arches and mosaic tiles, warm light, no text",
            "old library with ancient manuscripts, candlelight, no text",
            "medina of Fes rooftops at sunset, no text",
            "intricate Islamic geometric tile pattern, close-up, no text",
        ],
    },
    # ------------------------------------------------------------- Astronomie
    {
        "category": "Astronomie",
        "title": "Saturn würde in Wasser schwimmen",
        "hook": "Dieser Riesenplanet ist leichter als Wasser",
        "body": "Saturn ist riesig: Fast 760 Erden würden in ihn hineinpassen. Trotzdem ist er im Durchschnitt weniger dicht als Wasser. Das liegt daran, dass er hauptsächlich aus Wasserstoff und Helium besteht. Rein rechnerisch würde Saturn also in einer Badewanne schwimmen – wenn es eine gäbe, die groß genug ist. Natürlich ist das nur ein Gedankenspiel, aber es zeigt, wie anders Gasplaneten aufgebaut sind als unsere feste Erde.",
        "cta": "Welcher Planet ist dein Favorit?",
        "tags": ["Astronomie", "Saturn", "Planeten", "Weltraum", "Wissen"],
        "sources": ["NASA Science: Saturn Facts"],
        "image_prompts": [
            "planet Saturn with rings floating in calm water, surreal, no text",
            "Saturn rings close-up in space, cinematic, no text",
            "gas giant atmosphere swirling clouds, no text",
            "starfield with a distant ringed planet, no text",
        ],
    },
    {
        "category": "Astronomie",
        "title": "Fußspuren auf dem Mond bleiben Millionen Jahre",
        "hook": "Diese Fußspuren verschwinden fast nie",
        "body": "Auf der Erde sind Fußspuren nach dem nächsten Regen weg. Auf dem Mond nicht. Dort gibt es keine Luft, keinen Wind und kein Wasser, das sie verwischen könnte. Die Spuren der Apollo-Astronauten könnten deshalb laut NASA Millionen Jahre erhalten bleiben. Verändern können sie fast nur winzige Meteoriten, die über sehr lange Zeit auf die Oberfläche prasseln. Die ersten Schritte von 1969 sind also wahrscheinlich noch genau so da.",
        "cta": "Welche Spur würdest du auf dem Mond hinterlassen?",
        "tags": ["Astronomie", "Mond", "Apollo", "NASA", "Weltraum"],
        "sources": ["NASA: Apollo 11 bootprint"],
        "image_prompts": [
            "astronaut bootprint in grey lunar soil, sharp detail, no text",
            "lunar surface with Earth rising on the horizon, no text",
            "lunar module on the moon surface, cinematic, no text",
            "grey moon dust close-up under harsh sunlight, no text",
        ],
    },
    {
        "category": "Astronomie",
        "title": "Auf Merkur dauert ein Tag zwei Jahre",
        "hook": "Ein Tag hier dauert länger als zwei Jahre",
        "body": "Merkur umrundet die Sonne in nur 88 Erdtagen – ein Merkurjahr ist also kurz. Gleichzeitig dreht er sich extrem langsam um sich selbst. Von einem Sonnenaufgang bis zum nächsten vergehen auf Merkur etwa 176 Erdtage. Ein einziger Tag dort dauert also so lange wie zwei Merkurjahre. Dazu kommen extreme Temperaturen: am Tag über 400 Grad, in der Nacht unter minus 170 Grad.",
        "cta": "Könntest du einen Tag auf Merkur überstehen?",
        "tags": ["Astronomie", "Merkur", "Planeten", "Sonnensystem", "Weltraum"],
        "sources": ["NASA Science: Mercury Facts"],
        "image_prompts": [
            "planet Mercury close to the blazing sun, cinematic, no text",
            "cratered grey planet surface at sunrise, no text",
            "sun rising over a rocky alien horizon, no text",
            "solar system orbit diagram style artwork without labels, no text",
        ],
    },
    {
        "category": "Astronomie",
        "title": "Dieser Berg ist 2,5-mal so hoch wie der Everest",
        "hook": "Der höchste Berg steht nicht auf der Erde",
        "body": "Der Mount Everest ist knapp 8.849 Meter hoch. Auf dem Mars steht ein Vulkan, der ihn locker übertrifft: Olympus Mons. Er ragt rund 22 Kilometer in die Höhe, also etwa zweieinhalbmal so hoch wie der Everest. Und er ist riesig breit – ungefähr so groß wie ganz Polen. Weil seine Hänge so flach ansteigen, würdest du auf seinem Gipfel nicht einmal merken, dass du auf einem Berg stehst.",
        "cta": "Würdest du ihn besteigen?",
        "tags": ["Astronomie", "Mars", "Vulkan", "Olympus Mons", "Weltraum"],
        "sources": ["NASA Science: Olympus Mons"],
        "image_prompts": [
            "gigantic shield volcano on Mars seen from orbit, no text",
            "red Martian landscape with dust haze, cinematic, no text",
            "Mount Everest summit at sunrise for comparison, no text",
            "rover tracks on red Martian soil, no text",
        ],
    },
    {
        "category": "Astronomie",
        "title": "Du siehst die Sonne, wie sie vor 8 Minuten war",
        "hook": "Die Sonne, die du siehst, ist Vergangenheit",
        "body": "Licht ist schnell, aber nicht unendlich schnell. Von der Sonne bis zur Erde braucht es etwa acht Minuten und zwanzig Sekunden. Wenn du also in den Himmel schaust, siehst du die Sonne so, wie sie vor gut acht Minuten aussah. Würde sie in diesem Moment verschwinden, würdest du das erst acht Minuten später bemerken. Beim Sternenhimmel ist es noch extremer: Manche Sterne siehst du so, wie sie vor Tausenden Jahren waren.",
        "cta": "Was machst du in den nächsten acht Minuten?",
        "tags": ["Astronomie", "Sonne", "Licht", "Physik", "Weltraum"],
        "sources": ["NASA Space Place: How long does it take sunlight to reach Earth?"],
        "image_prompts": [
            "sun rays bursting over a horizon, cinematic, no text",
            "light beam traveling through space, artistic, no text",
            "person silhouette watching sunset, no text",
            "starry night sky over mountains, no text",
        ],
    },
    {
        "category": "Astronomie",
        "title": "Astronauten sehen 16 Sonnenaufgänge am Tag",
        "hook": "Hier geht die Sonne 16 Mal am Tag auf",
        "body": "Die Internationale Raumstation fliegt mit rund 28.000 Kilometern pro Stunde um die Erde. Für eine Runde braucht sie nur etwa anderthalb Stunden. Deshalb erleben Astronauten an einem einzigen Tag ungefähr 16 Sonnenaufgänge und 16 Sonnenuntergänge. Damit ihr Körper trotzdem einen Rhythmus hat, richten sie ihren Tag nach einer festen Uhrzeit aus und schlafen mit Augenmaske und abgedunkelten Kabinen.",
        "cta": "Könntest du so schlafen?",
        "tags": ["Astronomie", "ISS", "Raumfahrt", "Astronauten", "Weltraum"],
        "sources": ["NASA: International Space Station facts"],
        "image_prompts": [
            "sunrise over Earth seen from the International Space Station, no text",
            "space station orbiting Earth, cinematic, no text",
            "astronaut floating near a window with Earth view, no text",
            "thin blue atmosphere line at orbital sunrise, no text",
        ],
    },
    {
        "category": "Astronomie",
        "title": "Auf Uranus dauert eine Nacht 42 Jahre",
        "hook": "Hier dauert eine Nacht 42 Jahre",
        "body": "Uranus ist ein seltsamer Planet: Er liegt praktisch auf der Seite. Seine Achse ist so stark gekippt, dass er wie eine rollende Kugel um die Sonne zieht. Ein Umlauf dauert 84 Erdjahre. Deshalb bekommen seine Pole etwa 42 Jahre am Stück Sonnenlicht – und danach 42 Jahre Dunkelheit. Wer am Nordpol von Uranus geboren würde, könnte die erste Hälfte seines Lebens im Dunkeln verbringen.",
        "cta": "Würdest du lieber 42 Jahre Tag oder Nacht haben?",
        "tags": ["Astronomie", "Uranus", "Planeten", "Sonnensystem", "Weltraum"],
        "sources": ["NASA Science: Uranus Facts"],
        "image_prompts": [
            "pale blue-green planet Uranus tilted on its side, no text",
            "dark polar landscape under faint distant sun, no text",
            "icy giant planet with faint rings, cinematic, no text",
            "deep space with a small distant sun, no text",
        ],
    },
    {
        "category": "Astronomie",
        "title": "Es gibt mehr Sterne als Sandkörner auf der Erde",
        "hook": "Zähl alle Sandkörner – es gibt mehr Sterne",
        "body": "Wie viele Sandkörner liegen an allen Stränden der Erde? Unvorstellbar viele. Und doch gibt es nach gängigen Schätzungen im beobachtbaren Universum noch mehr Sterne. Allein unsere Milchstraße hat wohl 100 bis 400 Milliarden Sterne, und es gibt Hunderte Milliarden Galaxien. Genaue Zahlen kennt niemand, aber die Größenordnung zeigt: Selbst alle Strände der Welt reichen nicht, um die Sterne aufzuwiegen.",
        "cta": "Fühlst du dich jetzt klein oder groß?",
        "tags": ["Astronomie", "Sterne", "Universum", "Galaxien", "Wissen"],
        "sources": ["ESA: How many stars are there in the Universe?"],
        "image_prompts": [
            "handful of sand grains glowing like stars, macro, no text",
            "Milky Way over a quiet beach at night, no text",
            "deep field image of countless galaxies, no text",
            "silhouette of a person under a starry sky, no text",
        ],
    },
    {
        "category": "Astronomie",
        "title": "Auch der Mond hat Erdbeben",
        "hook": "Der Mond bebt – und zwar lange",
        "body": "Die Apollo-Astronauten haben auf dem Mond Messgeräte für Erschütterungen aufgestellt. Das Ergebnis überraschte: Auch der Mond bebt. Forscher sprechen von Mondbeben. Manche entstehen, wenn der Mond durch die Schwerkraft der Erde gedehnt wird, andere durch Temperaturwechsel oder Einschläge. Und weil der Mond trocken und starr ist, schwingen die Beben dort viel länger nach als auf der Erde – manchmal über eine Stunde.",
        "cta": "Hättest du gedacht, dass der Mond lebt?",
        "tags": ["Astronomie", "Mond", "Apollo", "Mondbeben", "Weltraum"],
        "sources": ["NASA Science: Moonquakes"],
        "image_prompts": [
            "cracked lunar surface with long shadows, no text",
            "seismometer instrument on the moon, retro NASA style, no text",
            "full moon over a dark landscape, cinematic, no text",
            "moon crater close-up, harsh light, no text",
        ],
    },
    # ----------------------------------------------------------- Wissenschaft
    {
        "category": "Wissenschaft",
        "title": "Alte Kirchenfenster fließen nicht",
        "hook": "Dieser Glas-Mythos ist falsch",
        "body": "Alte Kirchenfenster sind unten oft dicker als oben. Lange hieß es, Glas sei eine extrem langsame Flüssigkeit, die über Jahrhunderte nach unten fließt. Das stimmt nicht. Berechnungen zeigen: Bei Raumtemperatur würde das Fließen länger dauern als das Alter des Universums. Die ungleiche Dicke kommt von der alten Herstellung. Das Glas war von Anfang an ungleichmäßig, und die Glaser setzten die dicke Seite meist nach unten.",
        "cta": "Welchen Schul-Mythos hast du noch geglaubt?",
        "tags": ["Wissenschaft", "Glas", "Mythos", "Physik", "Wissen"],
        "sources": ["Zanotto, American Journal of Physics (1998): Do cathedral glasses flow?"],
        "image_prompts": [
            "old cathedral stained glass window with sunlight, no text",
            "uneven antique window glass with distorted view, no text",
            "glassblower shaping molten glass, warm light, no text",
            "close-up of rippled old glass texture, no text",
        ],
    },
    {
        "category": "Wissenschaft",
        "title": "Bananen sind leicht radioaktiv",
        "hook": "Diese Frucht ist leicht radioaktiv",
        "body": "Bananen enthalten viel Kalium. Ein winziger Teil davon ist Kalium-40, eine natürlich radioaktive Form. Deshalb ist jede Banane minimal radioaktiv. Gefährlich ist das überhaupt nicht: Dein Körper enthält selbst Kalium und gibt Überschüsse wieder ab. Die Menge ist so klein, dass man in der Wissenschaft scherzhaft von der Bananen-Dosis spricht, um zu zeigen, wie gering manche Strahlungswerte sind.",
        "cta": "Isst du deine Banane trotzdem?",
        "tags": ["Wissenschaft", "Banane", "Radioaktivität", "Physik", "Ernährung"],
        "sources": ["US Environmental Protection Agency: Radiation in food"],
        "image_prompts": [
            "bunch of ripe bananas with soft glow, studio light, no text",
            "Geiger counter next to fruit on a table, no text",
            "banana sliced on a wooden board, macro, no text",
            "abstract atoms glowing in green light, no text",
        ],
    },
    {
        "category": "Wissenschaft",
        "title": "Ein Blitz ist nur so dick wie ein Daumen",
        "hook": "Ein Blitz ist nur daumendick",
        "body": "Ein Blitz wirkt riesig, wenn er über den Himmel zuckt. Der eigentliche Blitzkanal ist aber erstaunlich dünn: nur etwa zwei bis drei Zentimeter breit, ungefähr so dick wie ein Daumen. Dass er so breit aussieht, liegt an seiner enormen Helligkeit, die das Licht in deinem Auge überstrahlt. Dafür kann ein Blitz kilometerlang sein. Ein dünner Faden voller Energie, der die Luft schlagartig erhitzt – deshalb der Donner.",
        "cta": "Hast du schon mal einen Blitz aus der Nähe gesehen?",
        "tags": ["Wissenschaft", "Blitz", "Gewitter", "Wetter", "Physik"],
        "sources": ["NOAA National Severe Storms Laboratory: Lightning basics"],
        "image_prompts": [
            "single lightning bolt over a dark landscape, long exposure, no text",
            "storm clouds at night lit from inside, no text",
            "thumb silhouette against lightning sky, no text",
            "rain-soaked field under a thunderstorm, cinematic, no text",
        ],
    },
    {
        "category": "Wissenschaft",
        "title": "Darum friert ein See nie von unten zu",
        "hook": "Wasser verhält sich hier anders als alles andere",
        "body": "Die meisten Stoffe werden dichter, wenn sie kälter werden. Wasser nicht ganz: Am schwersten ist es bei etwa vier Grad. Wird es kälter, steigt es wieder nach oben, und Eis ist sogar leichter als Wasser. Deshalb gefriert ein See von oben. Die Eisschicht wirkt wie ein Deckel und schützt das Wasser darunter. So können Fische auch einen harten Winter überleben.",
        "cta": "Hättest du gedacht, dass Fische dem Eis ihr Leben verdanken?",
        "tags": ["Wissenschaft", "Wasser", "Eis", "Physik", "Natur"],
        "sources": ["USGS Water Science School: Ice, snow, and glaciers"],
        "image_prompts": [
            "frozen lake with clear ice and dark water below, no text",
            "fish swimming under a layer of ice, no text",
            "winter lake at sunrise with frost, cinematic, no text",
            "cracked ice surface close-up, no text",
        ],
    },
    {
        "category": "Wissenschaft",
        "title": "Unter Wasser ist Schall viermal schneller",
        "hook": "Unter Wasser ist Schall viermal schneller",
        "body": "In der Luft bewegt sich Schall mit etwa 343 Metern pro Sekunde. Im Wasser ist er viel schneller, ungefähr 1.500 Meter pro Sekunde – also gut viermal so schnell. Der Grund: Wasser ist dichter und die Teilchen geben die Schwingung schneller weiter. Deshalb hören Wale einander über riesige Entfernungen. Für uns Menschen ist das unter Wasser übrigens verwirrend: Wir können kaum noch erkennen, aus welcher Richtung ein Geräusch kommt.",
        "cta": "Hast du unter Wasser schon mal etwas Seltsames gehört?",
        "tags": ["Wissenschaft", "Schall", "Wasser", "Physik", "Meer"],
        "sources": ["NOAA Ocean Service: How far does sound travel in the ocean?"],
        "image_prompts": [
            "underwater view with sound waves rippling, artistic, no text",
            "humpback whale singing in deep blue ocean, no text",
            "diver underwater in sunbeams, no text",
            "ocean surface with gentle waves, no text",
        ],
    },
    {
        "category": "Wissenschaft",
        "title": "Dein Bleistift ist ein Verwandter des Diamanten",
        "hook": "Bleistift und Diamant sind fast dasselbe",
        "body": "In einem Bleistift steckt kein Blei, sondern Graphit. Und Graphit besteht aus reinem Kohlenstoff – genau wie ein Diamant. Der Unterschied liegt nur in der Anordnung der Atome. Im Graphit liegen sie in Schichten, die leicht übereinander gleiten, deshalb schreibt der Stift. Im Diamanten sind sie fest in alle Richtungen verbunden, deshalb ist er so hart. Gleicher Stoff, völlig andere Eigenschaften.",
        "cta": "Schreibst du jetzt anders mit deinem Bleistift?",
        "tags": ["Wissenschaft", "Chemie", "Diamant", "Graphit", "Kohlenstoff"],
        "sources": ["Royal Society of Chemistry: Carbon allotropes"],
        "image_prompts": [
            "sharpened graphite pencil next to a sparkling diamond, studio, no text",
            "macro of pencil tip on paper, no text",
            "diamond crystal refracting light, no text",
            "abstract carbon atom lattice glowing, no text",
        ],
    },
    # ------------------------------------------------------------ Weltrekorde
    {
        "category": "Weltrekorde",
        "title": "56,7 Grad: der heißeste Ort der Erde",
        "hook": "Hier wurde es 56,7 Grad heiß",
        "body": "Die höchste offiziell anerkannte Lufttemperatur der Erde wurde am 10. Juli 1913 im Death Valley in Kalifornien gemessen: 56,7 Grad Celsius. Die Weltorganisation für Meteorologie führt diesen Wert als Rekord. Das Tal liegt teilweise unter dem Meeresspiegel und ist von Bergen umgeben, die die Hitze festhalten. Selbst nachts kühlt es im Sommer dort oft kaum unter 30 Grad ab.",
        "cta": "Wie viel Hitze hältst du aus?",
        "tags": ["Weltrekorde", "Hitze", "Death Valley", "Wetter", "USA"],
        "sources": ["WMO Weather and Climate Extremes Archive"],
        "image_prompts": [
            "cracked salt flats of Death Valley under blazing sun, no text",
            "heat shimmer over desert road, cinematic, no text",
            "thermometer in desert sand, no text",
            "barren desert mountains at noon, no text",
        ],
    },
    {
        "category": "Weltrekorde",
        "title": "Minus 89,2 Grad: hier wurde es am kältesten",
        "hook": "Minus 89,2 Grad – gemessen auf der Erde",
        "body": "Am 21. Juli 1983 maßen Forscher an der russischen Wostok-Station in der Antarktis minus 89,2 Grad Celsius. Das ist die tiefste je direkt gemessene Lufttemperatur auf der Erde. Die Station liegt mitten auf dem Eisschild, über 3.000 Meter hoch. Bei solchen Temperaturen würde ungeschützte Haut in kürzester Zeit erfrieren, und selbst Diesel wird zähflüssig.",
        "cta": "Was würdest du anziehen?",
        "tags": ["Weltrekorde", "Kälte", "Antarktis", "Wetter", "Wostok"],
        "sources": ["WMO Weather and Climate Extremes Archive"],
        "image_prompts": [
            "remote research station on Antarctic ice plateau, no text",
            "ice crystals glittering in polar air, macro, no text",
            "endless white ice sheet under pale sun, no text",
            "frost-covered fabric close-up, no text",
        ],
    },
    {
        "category": "Weltrekorde",
        "title": "Dieser Mann war 2,72 Meter groß",
        "hook": "Der größte Mensch, der je gemessen wurde",
        "body": "Robert Wadlow aus den USA ist der größte Mensch, dessen Größe zuverlässig gemessen wurde: 2,72 Meter. Er wuchs wegen einer Überfunktion der Hirnanhangdrüse sein Leben lang weiter. Seine Schuhe hatten Größe 76, und er brauchte Schienen an den Beinen, um gehen zu können. Wadlow galt als freundlicher, ruhiger Mensch. Er starb 1940 mit nur 22 Jahren an einer Infektion.",
        "cta": "Wie groß bist du?",
        "tags": ["Weltrekorde", "Größter Mensch", "Robert Wadlow", "Guinness", "Rekord"],
        "sources": ["Guinness World Records: Tallest man ever"],
        "image_prompts": [
            "vintage doorway with tall height markings, sepia, no text",
            "oversized shoe next to normal shoe, vintage style, no text",
            "1930s small town street, black and white film look, no text",
            "measuring tape against a wall, no text",
        ],
    },
    {
        "category": "Weltrekorde",
        "title": "Diese Frau wurde 122 Jahre alt",
        "hook": "Sie erlebte Fahrrad, Auto und Internet",
        "body": "Jeanne Calment aus Frankreich ist der älteste Mensch, dessen Alter zuverlässig belegt ist: 122 Jahre und 164 Tage. Sie wurde 1875 geboren und starb 1997. Als Jugendliche traf sie den Maler Vincent van Gogh in ihrer Heimatstadt Arles. Sie erlebte die Erfindung des Autos, zwei Weltkriege und die ersten Jahre des Internets. Fahrrad fuhr sie angeblich noch mit 100.",
        "cta": "Wie alt willst du werden?",
        "tags": ["Weltrekorde", "Ältester Mensch", "Jeanne Calment", "Frankreich", "Guinness"],
        "sources": ["Guinness World Records: Oldest person ever"],
        "image_prompts": [
            "old town of Arles in southern France, sunny, no text",
            "vintage bicycle against a stone wall, no text",
            "hand of an elderly woman holding a teacup, warm light, no text",
            "timeline of old photographs on a table, no text",
        ],
    },
    {
        "category": "Weltrekorde",
        "title": "Usain Bolt lief fast 45 km/h schnell",
        "hook": "Ein Mensch, fast so schnell wie ein Auto in der Stadt",
        "body": "2009 lief Usain Bolt in Berlin die 100 Meter in 9,58 Sekunden – Weltrekord bis heute. Auf dem schnellsten Abschnitt erreichte er dabei fast 45 Kilometer pro Stunde. Damit wäre er in einer Tempo-30-Zone geblitzt worden. Für die ganze Strecke brauchte er nur gut 41 Schritte. Seine Größe von 1,95 Metern galt vorher eher als Nachteil für Sprinter – Bolt bewies das Gegenteil.",
        "cta": "Wie schnell läufst du die 100 Meter?",
        "tags": ["Weltrekorde", "Usain Bolt", "Sprint", "Leichtathletik", "Berlin"],
        "sources": ["World Athletics: 100m men's world record", "IAAF Biomechanics Report Berlin 2009"],
        "image_prompts": [
            "sprinter bursting from starting blocks on a red track, no text",
            "stadium at night with bright floodlights, no text",
            "running shoes on track lines close-up, no text",
            "motion blur of a sprinter, cinematic, no text",
        ],
    },
    {
        "category": "Weltrekorde",
        "title": "Der Everest würde im Marianengraben versinken",
        "hook": "Der höchste Berg passt hier hinein",
        "body": "Der tiefste bekannte Punkt der Ozeane ist das Challengertief im Marianengraben, fast 11.000 Meter unter dem Meeresspiegel. Würde man den Mount Everest dort hineinstellen, läge sein Gipfel noch rund zwei Kilometer unter der Wasseroberfläche. Unten herrscht ein Druck, der dem Gewicht von mehreren Autos auf jedem Daumennagel entspricht. Trotzdem fanden Forscher dort Leben, zum Beispiel winzige Flohkrebse.",
        "cta": "Würdest du da runter tauchen?",
        "tags": ["Weltrekorde", "Marianengraben", "Ozean", "Tiefsee", "Mount Everest"],
        "sources": ["NOAA Ocean Exploration: Mariana Trench"],
        "image_prompts": [
            "deep dark ocean trench with faint light, no text",
            "submersible lights in the deep sea, cinematic, no text",
            "Mount Everest peak partly covered by clouds, no text",
            "tiny translucent amphipod on dark background, macro, no text",
        ],
    },
    # ----------------------------------------------------------------- Natur
    {
        "category": "Natur",
        "title": "Im Fell von Faultieren wachsen Algen",
        "hook": "Dieses Tier ist so langsam, dass es grün wird",
        "body": "Faultiere bewegen sich so langsam und hängen so lange im Regenwald, dass in ihrem Fell Algen wachsen. Dadurch schimmert ihr Fell oft grünlich. Das hilft ihnen sogar bei der Tarnung zwischen den Blättern. In ihrem Fell leben außerdem Motten und andere kleine Tiere – ein ganzes Mini-Ökosystem. Und ja, Faultiere sind wirklich langsam: Auf dem Boden schaffen sie oft nur ein paar Meter pro Minute.",
        "cta": "An welchen Tagen bist du ein Faultier?",
        "tags": ["Natur", "Faultier", "Regenwald", "Tiere", "Algen"],
        "sources": ["Smithsonian Magazine: Sloths, algae and moths"],
        "image_prompts": [
            "sloth hanging from a tree in rainforest, greenish fur, no text",
            "close-up of sloth face with soft light, no text",
            "lush rainforest canopy with mist, no text",
            "macro of green algae texture, no text",
        ],
    },
    {
        "category": "Natur",
        "title": "Das Herz eines Blauwals wiegt rund 180 Kilo",
        "hook": "Dieses Herz wiegt so viel wie zwei Menschen",
        "body": "Der Blauwal ist das größte Tier, das je gelebt hat. Entsprechend groß ist sein Herz: Ein konserviertes Blauwalherz im Royal Ontario Museum in Kanada wog rund 180 Kilogramm. Es ist etwa so groß wie ein kleines Auto. Beim Tauchen schlägt es extrem langsam, manchmal nur zwei Mal pro Minute, um Sauerstoff zu sparen. Und sein Herzschlag ist kilometerweit unter Wasser messbar.",
        "cta": "Hättest du gedacht, dass ein Herz so groß sein kann?",
        "tags": ["Natur", "Blauwal", "Herz", "Meer", "Tiere"],
        "sources": ["Royal Ontario Museum: Blue whale heart", "Goldbogen et al., PNAS (2019)"],
        "image_prompts": [
            "blue whale gliding through deep blue ocean, no text",
            "silhouette of a whale against sunlight from above, no text",
            "museum hall with large whale skeleton, no text",
            "ocean surface with whale blow spray, no text",
        ],
    },
    {
        "category": "Natur",
        "title": "Seeotter halten sich im Schlaf an den Pfoten",
        "hook": "Diese Tiere schlafen Hand in Hand",
        "body": "Seeotter schlafen auf dem Rücken im Wasser. Damit sie dabei nicht auseinandertreiben, halten sich manche an den Pfoten fest oder wickeln sich in Seetang ein, der am Meeresgrund verankert ist. Oft liegen viele Otter zusammen in Gruppen, die man Flöße nennt. Ihr dichtes Fell hält sie warm: Seeotter haben das dichteste Fell aller Tiere, mit bis zu einer Million Haaren pro Quadratzentimeter.",
        "cta": "Wem würdest du im Schlaf die Hand geben?",
        "tags": ["Natur", "Seeotter", "Tiere", "Meer", "Süß"],
        "sources": ["Monterey Bay Aquarium: Sea otter facts"],
        "image_prompts": [
            "two sea otters floating on their backs holding paws, no text",
            "kelp forest swaying underwater, sunlight, no text",
            "group of sea otters resting in calm water, no text",
            "close-up of dense otter fur, macro, no text",
        ],
    },
    {
        "category": "Natur",
        "title": "Diese Pflanze wächst fast einen Meter am Tag",
        "hook": "Hier kannst du beim Wachsen zusehen",
        "body": "Manche Bambusarten gehören zu den am schnellsten wachsenden Pflanzen der Welt. Unter idealen Bedingungen kann ein Spross bis zu 91 Zentimeter an einem einzigen Tag zulegen. Das sind fast vier Zentimeter pro Stunde. Bambus ist übrigens kein Baum, sondern ein Gras. Weil er so schnell nachwächst und sehr stabil ist, wird er in vielen Ländern als Baumaterial genutzt, sogar für Gerüste an Hochhäusern.",
        "cta": "Was würdest du aus Bambus bauen?",
        "tags": ["Natur", "Bambus", "Pflanzen", "Rekord", "Wachstum"],
        "sources": ["Guinness World Records: Fastest growing plant"],
        "image_prompts": [
            "dense bamboo forest with light rays, no text",
            "young bamboo shoot emerging from soil, macro, no text",
            "bamboo scaffolding on a building, no text",
            "green bamboo stalks swaying in wind, no text",
        ],
    },
    {
        "category": "Natur",
        "title": "Kolibris können rückwärts fliegen",
        "hook": "Der einzige Vogel, der rückwärts fliegt",
        "body": "Kolibris sind die einzigen Vögel, die wirklich gezielt rückwärts fliegen können. Ihre Flügel schlagen je nach Art bis zu 80 Mal pro Sekunde und drehen sich dabei im Schultergelenk fast wie ein Propeller. So können sie in der Luft stehen, seitwärts fliegen und rückwärts aus einer Blüte herausmanövrieren. Dafür brauchen sie enorm viel Energie und müssen täglich ein Vielfaches ihres Körpergewichts an Nektar trinken.",
        "cta": "Welcher Vogel fasziniert dich am meisten?",
        "tags": ["Natur", "Kolibri", "Vögel", "Tiere", "Fliegen"],
        "sources": ["Smithsonian's National Zoo: Hummingbird facts"],
        "image_prompts": [
            "hummingbird hovering near a red flower, high speed photo, no text",
            "blurred hummingbird wings in motion, macro, no text",
            "tropical garden with flowers, soft light, no text",
            "hummingbird feeding on nectar, close-up, no text",
        ],
    },
    # -------------------------------------------------------------- Biologie
    {
        "category": "Biologie",
        "title": "In dir leben so viele Bakterien wie du Zellen hast",
        "hook": "Du bist nur zur Hälfte du",
        "body": "Dein Körper besteht aus etwa 30 Billionen eigenen Zellen. Dazu kommen ungefähr genauso viele Bakterien, die vor allem in deinem Darm leben. Forscher schätzen das Verhältnis heute auf etwa eins zu eins. Die meisten dieser Bakterien sind nützlich: Sie helfen bei der Verdauung, bilden Vitamine und trainieren dein Immunsystem. Zusammen wiegen sie übrigens nur etwa 200 Gramm.",
        "cta": "Hättest du gedacht, dass du so viele Mitbewohner hast?",
        "tags": ["Biologie", "Bakterien", "Körper", "Darm", "Gesundheit"],
        "sources": ["Sender, Fuchs & Milo, PLOS Biology (2016)"],
        "image_prompts": [
            "colorful microscopic bacteria illustration, no text",
            "abstract human silhouette with glowing particles, no text",
            "petri dish with bacterial colonies, lab light, no text",
            "microscope in a laboratory, cinematic, no text",
        ],
    },
    {
        "category": "Biologie",
        "title": "Eine Giraffe hat so viele Halswirbel wie du",
        "hook": "Gleiche Zahl – völlig anderer Hals",
        "body": "Der Hals einer Giraffe kann fast zwei Meter lang sein. Trotzdem hat sie genauso viele Halswirbel wie du: sieben. Fast alle Säugetiere haben sieben Halswirbel, egal ob Maus, Mensch oder Giraffe. Der Unterschied liegt in der Größe: Bei der Giraffe ist jeder einzelne Wirbel bis zu 25 Zentimeter lang. Die Natur hat also nicht mehr Teile eingebaut, sondern die vorhandenen einfach verlängert.",
        "cta": "Welches Tier würdest du gern für einen Tag sein?",
        "tags": ["Biologie", "Giraffe", "Säugetiere", "Anatomie", "Tiere"],
        "sources": ["Smithsonian's National Zoo: Giraffe facts"],
        "image_prompts": [
            "giraffe neck against blue sky, no text",
            "giraffe skeleton in a museum, no text",
            "giraffes on the African savanna at sunset, no text",
            "close-up of giraffe head and eye, no text",
        ],
    },
    {
        "category": "Biologie",
        "title": "Dein Herz schlägt rund 100.000 Mal am Tag",
        "hook": "Dein Herz macht nie Pause",
        "body": "In Ruhe schlägt dein Herz etwa 60 bis 100 Mal pro Minute. Hochgerechnet sind das rund 100.000 Schläge an einem einzigen Tag, ohne dass du daran denken musst. Dabei pumpt es täglich ungefähr 7.000 Liter Blut durch deinen Körper. Über ein ganzes Leben kommen so mehr als zwei Milliarden Herzschläge zusammen. Ein Muskel so groß wie eine Faust, der niemals Urlaub macht.",
        "cta": "Was tust du heute für dein Herz?",
        "tags": ["Biologie", "Herz", "Körper", "Gesundheit", "Wissen"],
        "sources": ["American Heart Association: How the heart works"],
        "image_prompts": [
            "anatomical heart illustration glowing red, no text",
            "heartbeat line on a monitor in a dark room, no text",
            "runner at sunrise with visible breath, no text",
            "hands forming a heart shape against sunset, no text",
        ],
    },
    # ------------------------------------------------------------ Psychologie
    {
        "category": "Psychologie",
        "title": "Darum siehst du plötzlich überall dasselbe Auto",
        "hook": "Neues Auto gekauft – plötzlich ist es überall",
        "body": "Kennst du das? Du interessierst dich für ein bestimmtes Auto, und plötzlich fährt es überall herum. Es sind nicht mehr Autos geworden, dein Gehirn achtet nur stärker darauf. Das nennt man Frequenzillusion oder Baader-Meinhof-Phänomen. Dein Gehirn filtert ständig, was wichtig ist. Sobald etwas Bedeutung bekommt, fällt es dir auf – und du hältst es für häufiger, als es wirklich ist.",
        "cta": "Was siehst du gerade überall?",
        "tags": ["Psychologie", "Gehirn", "Wahrnehmung", "Frequenzillusion", "Alltag"],
        "sources": ["Arnold Zwicky (2005): Just between Dr. Language and I – frequency illusion"],
        "image_prompts": [
            "busy city street with one red car highlighted, no text",
            "person noticing something in a crowd, cinematic, no text",
            "abstract brain with light filters, no text",
            "parking lot seen from above, no text",
        ],
    },
    {
        "category": "Psychologie",
        "title": "Darum kannst du dich nicht selbst kitzeln",
        "hook": "Versuch es – es klappt nicht",
        "body": "Du kannst dich selbst nicht richtig kitzeln. Der Grund liegt in deinem Gehirn. Wenn du dich bewegst, sagt dein Gehirn voraus, was du gleich spüren wirst. Weil die Berührung erwartet ist, wird das Gefühl gedämpft. Forscher in London haben das mit einem Roboterarm getestet: Kam die Berührung leicht verzögert oder verändert, fühlte sie sich wieder kitzliger an. Überraschung ist also der Schlüssel.",
        "cta": "Hast du es gerade ausprobiert?",
        "tags": ["Psychologie", "Gehirn", "Kitzeln", "Wahrnehmung", "Forschung"],
        "sources": ["Blakemore, Wolpert & Frith, Nature Neuroscience (1998)"],
        "image_prompts": [
            "person laughing while being tickled, warm light, no text",
            "feather touching skin, macro, no text",
            "abstract brain with prediction signals glowing, no text",
            "robotic arm in a research lab, no text",
        ],
    },
    # ------------------------------------------------------------ Technologie
    {
        "category": "Technologie",
        "title": "Die erste Webcam zeigte eine Kaffeemaschine",
        "hook": "Die erste Webcam hatte nur ein Ziel: Kaffee",
        "body": "An der Universität Cambridge hatten Forscher 1991 ein Problem: Sie liefen umsonst zur Kaffeemaschine, weil die Kanne leer war. Also richteten sie eine Kamera auf die Maschine und zeigten das Bild im eigenen Netzwerk. Ab 1993 war die Kaffeekanne im Internet zu sehen – eine der ersten Webcams überhaupt. Menschen aus aller Welt schauten zu. Als die Maschine 2001 abgeschaltet wurde, wurde sie sogar versteigert.",
        "cta": "Was hättest du damals im Internet gestreamt?",
        "tags": ["Technologie", "Internet", "Webcam", "Cambridge", "Geschichte"],
        "sources": ["University of Cambridge Computer Laboratory: Trojan Room coffee pot"],
        "image_prompts": [
            "vintage coffee filter machine in an old university lab, no text",
            "early 1990s computer monitor with grainy video, no text",
            "steaming coffee pot close-up, warm light, no text",
            "old university corridor in Cambridge, no text",
        ],
    },
]
